### ISSUE TITLE
Exception while playing on a vanilla server

### ISSUE THREAD

**Issue by Polyana-Fontes** [Ordinastie/MalisisDoors#121]
This happens when we are playing a vanilla server with this mod installed. This might also happens on modded servers without this mod.

Crash-Report:
http://pastebin.com/YB9k6dQR

That happened after an explosion near lava.

I had to disable modifyVanillaDoors but I like that feature :( That should work on vanilla servers...
```properties
B:config.modifyVanillaDoors=false
```

```java
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:flowing_lava, properties=[level]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDirection(FenceGateTileEntity.java:85)
	at net.malisis.doors.renderer.FenceGateRenderer.setup(FenceGateRenderer.java:160)
	at net.malisis.doors.renderer.FenceGateRenderer.render(FenceGateRenderer.java:144)
	at net.malisis.core.renderer.MalisisRenderer.func_180535_a(MalisisRenderer.java:438)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:168)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:141)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:997)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.6.
