### ISSUE TITLE
Rendering Crash?

### ISSUE THREAD

**Issue by ukdyl94** [Ordinastie/MalisisDoors#168]
`java.util.ConcurrentModificationException
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1617)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.malisis.core.renderer.AnimatedRenderer.render(AnimatedRenderer.java:104)
	at net.malisis.core.renderer.MalisisRenderer.renderWorldLastEvent(MalisisRenderer.java:496)
	at net.malisis.core.registry.ClientRegistry.onRenderLast(ClientRegistry.java:116)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_732_ClientRegistry_onRenderLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

https://pastebin.com/S6S2F095

**Comment by itsmeow** [comment]
Also having this issue. https://pastebin.com/NXEcaxWw
MC Version 1.12.2,
MalisisCore 1.12.2-6.4.0
MalisisDoors 1.12.2-7.3.0
