### ISSUE TITLE
MD crashes during random/Breaking doors/trapdoors.

### ISSUE THREAD

**Issue by tehbasshunter** [Ordinastie/MalisisDoors#194]
I use MultiMC and this is the error that I usually tend to see with mentioned instances.  
  
I have MC 6.1.7 and MD 7.1.1 (Which has the mcmod.info listed as 7.1.0 from the CF download)  
  
```[19:34:05] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.world.World.func_72939_s(World.java:1844) ~[amu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:stone, properties=[variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[awu$a.class:?]
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDirection(FenceGateTileEntity.java:85) ~[FenceGateTileEntity.class:1.12.2-7.1.1]
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:151) ~[FenceGateTileEntity.class:1.12.2-7.1.1]
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:46) ~[FenceGateTileEntity.class:1.12.2-7.1.1]
	at net.malisis.doors.tileentity.DoorTileEntity.isDoubleDoorPowered(DoorTileEntity.java:184) ~[DoorTileEntity.class:1.12.2-7.1.1]
	at net.malisis.doors.tileentity.DoorTileEntity.func_73660_a(DoorTileEntity.java:419) ~[DoorTileEntity.class:1.12.2-7.1.1]
	at net.minecraft.world.World.func_72939_s(World.java:1829) ~[amu.class:?]
	... 18 more
  
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:stone, properties=[variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDirection(FenceGateTileEntity.java:85)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:151)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:46)
	at net.malisis.doors.tileentity.DoorTileEntity.isDoubleDoorPowered(DoorTileEntity.java:184)
	at net.malisis.doors.tileentity.DoorTileEntity.func_73660_a(DoorTileEntity.java:419)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
  
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDirection(FenceGateTileEntity.java:85)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:151)
	at net.malisis.doors.tileentity.FenceGateTileEntity.getDoubleDoor(FenceGateTileEntity.java:46)
	at net.malisis.doors.tileentity.DoorTileEntity.isDoubleDoorPowered(DoorTileEntity.java:184)
	at net.malisis.doors.tileentity.DoorTileEntity.func_73660_a(DoorTileEntity.java:419)

**Comment by Ordinastie** [comment]
That should really never happen. Can you replicate the issue reliably ?

**Comment by tehbasshunter** [comment]
I'd have to readd it to try again since it was happening frequently enough to warrant removing/disabling it.

**Comment by tehbasshunter** [comment]
Took a stab trying to replicate it and while it was able happen once I can't seem to figure out the circumstances for the crash.

**Comment by Ordinastie** [comment]
Does it only happen when you break stuff ? Does it happen with only MalisisDoors installed ?

**Comment by tehbasshunter** [comment]
Only when breaking trapdoors/doors.  I've not had the issue since removing it.

**Comment by Ordinastie** [comment]
Does it happen with only MalisisDoors installed ?

**Comment by tehbasshunter** [comment]
I can't seem to replicate it.  
  
The only circumstance that I can definitively say contribute to it outside of your mod being listed as the cause it that it happens with any structure from structurepro and using the morningstart/katar from projectE to break it.  
  
Other than that it's just random.

**Comment by Ordinastie** [comment]
Shouldn't have been fixed in latest updates.
