### ISSUE TITLE
Crash with pressure plates and doors

### ISSUE THREAD

**Issue by overfriended** [Ordinastie/MalisisDoors#265]
Hi, this seems to be only me, but on a mac I can't walk on a pressure plate to open a door. The error is below with Malisis versions.

MalisisCore version: 6.4.0
MalisisDoors version: 7.3.0

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at net.malisis.core.util.DoubleKeyMap.getEntry(DoubleKeyMap.java:88) ~[DoubleKeyMap.class:1.12.2-6.4.0]
	at net.malisis.core.util.DoubleKeyMap.get(DoubleKeyMap.java:111) ~[DoubleKeyMap.class:1.12.2-6.4.0]
	at net.malisis.core.util.syncer.handlers.DefaultSyncHandler.getObjectData(DefaultSyncHandler.java:53) ~[DefaultSyncHandler.class:1.12.2-6.4.0]
	at net.malisis.core.util.syncer.message.SyncerMessage$Packet.fromBytes(SyncerMessage.java:136) ~[SyncerMessage$Packet.class:1.12.2-6.4.0]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:107) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:38) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]

**Comment by overfriended** [comment]
Edit: I also cannot break the pressure plates.

**Comment by overfriended** [comment]
This all happens near a door. It has to be right next to it.
