### ISSUE TITLE
Crashes When Installed With The Mod Repose

### ISSUE THREAD

**Issue by Junrall** [Ordinastie/MalisisDoors#30]
Hi,
Upon start-up, I get the following error when Malisis Doors are installed alongside Repose (http://minecraft.curseforge.com/mc-mods/220524-repose). Here is the error log with just the two mods and their dependencies:

---- Minecraft Crash Report ----
// My bad.

Time: 4/25/15 9:49 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Expecting a stackmap frame at branch target 21
Exception Details:
  Location:
    net/malisis/doors/door/block/Door.func_149695_a(Lnet/minecraft/world/World;IIILnet/minecraft/block/Block;)V @4: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ac1 000b 9a00 112a 2b1c 1d15 0419 05b7
    0x0000010: 00f8 a700 1a2b 1c1d 1504 1905 12f9 12fa
    0x0000020: 12fb b801 012a c000 0bb8 0107 b1       

	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:250)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 21
Exception Details:
  Location:
    net/malisis/doors/door/block/Door.func_149695_a(Lnet/minecraft/world/World;IIILnet/minecraft/block/Block;)V @4: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ac1 000b 9a00 112a 2b1c 1d15 0419 05b7
    0x0000010: 00f8 a700 1a2b 1c1d 1504 1905 12f9 12fa
    0x0000020: 12fb b801 012a c000 0bb8 0107 b1       

	at net.malisis.doors.door.DoorDescriptor.create(DoorDescriptor.java:303)
	at net.malisis.doors.Registers.registerVanillaDoors(Registers.java:124)
	at net.malisis.doors.Registers.init(Registers.java:86)
	at net.malisis.doors.MalisisDoors.preInit(MalisisDoors.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:531)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 873503144 bytes (833 MB) / 1300234240 bytes (1240 MB) up to 3773300736 bytes (3598 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4048m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.112.1374 Minecraft Forge 10.13.3.1374 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.112.1374} [Forge Mod Loader] (forge-1.7.10-10.13.3.1374-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1374} [Minecraft Forge] (forge-1.7.10-10.13.3.1374-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
	farseek{1.0.5} [Farseek] (Farseek-1.0.5.jar) Unloaded->Constructed->Pre-initialized
	malisiscore{1.7.10-0.11.4} [MalisisCore] (malisiscore-1.7.10-0.11.4.jar) Unloaded->Constructed->Pre-initialized
	malisisdoors{1.7.10-1.7.1} [Malisis' Doors] (malisisdoors-1.7.10-1.7.1.jar) Unloaded->Constructed->Errored
	repose{1.2.2} [Repose] (Repose-1.2.2.jar) Unloaded->Constructed->Pre-initialized

**Comment by Junrall** [comment]
I'm going to post this to Repose owner as well. I just noticed that he wants people to let him know if there is any issues between his mod and any other mod.

~June~

**Comment by Ordinastie** [comment]
I think it's a Repose issue. Looks like it messes with stuff it shouldn't.
